import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClientThemeProvider } from "@client/components/ClientThemeProvider";
import { ClientLocalizationProvider } from "@client/components/ClientLocalizationProvider";
import { Header } from "@client/components/Header";
import { Footer } from "@client/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    //Определяет заголовок по умолчанию для дочерних сегментов. Он игнорирует title.template из родительских сегментов.
    //absolute: "Cosmetologist Planner",

    //Резервное название для дочерних сегментов маршрута, в которых title не задан.
    default: "Cosmetologist Planner",

    //Применяется к дочерним сегментам маршрута.
    //Вместо шаблона %s будет использовано значение title дочерней страницы.
    template: "%s | Cosmetologist Planner",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClientLocalizationProvider>
          <ClientThemeProvider>
            <Header />
            {children}
            <Footer />
          </ClientThemeProvider>
        </ClientLocalizationProvider>
      </body>
    </html>
  );
}
