import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClientThemeProvider } from "@client/components/ClientThemeProvider";
import { ClientLocalizationProvider } from "@client/components/ClientLocalizationProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClientLocalizationProvider>
          <ClientThemeProvider>{children}</ClientThemeProvider>
        </ClientLocalizationProvider>
      </body>
    </html>
  );
}
